version: 2
machine:
  environment:
    _JAVA_OPTIONS: "-Xms1024m -Xmx1024m"
defaults: &defaults
  machine:
    # If updating to a JDK9 image, ensure that build-deploy still tests against JDK8 until we drop support for it
    image: circleci/classic:201711-01

  working_directory: ~/glowstone

  environment:
    MAVEN_OPTS: -Xmx1024m
jobs:
    build:
        <<: *defaults
        steps:
            - run: mvn --version
            - run: java -version

            - checkout

            - run: git config --global user.email "mastercoms@tutanota.de"
            - run: git config --global user.name "mastercoms"

            - restore_cache:
                keys:
                    # Use cache for this pom
                    - linkstone-{{ checksum "linkstone-shim/pom.xml" }}-{{ checksum "linkstone-runtime/pom.xml" }}
                    # Fallback to latest cache is an exact match is not found
                    - linkstone-

            - run: ./build-external.sh
            #- run: mvn -am -T 1C -B dependency:go-offline

            - save_cache:
                paths:
                    - ~/.m2
                key: linkstone-{{ checksum "linkstone-shim/pom.xml" }}-{{ checksum "linkstone-runtime/pom.xml" }}

            - run: mvn -am -T 1C -B package

            - store_artifacts:
                path: linkstone-shim/target/linkstone-shim-1.0.0.jar
                destination: linkstone-shim-1.0.0.jar

    build-deploy:
        <<: *defaults
        steps:
            - run: mvn --version
            - run: java -version

            - checkout

            - run: git config --global user.email "mastercoms@tutanota.de"
            - run: git config --global user.name "mastercoms"

            - restore_cache:
                keys:
                    # Use cache for this pom
                    - linkstone-{{ checksum "linkstone-shim/pom.xml" }}-{{ checksum "linkstone-runtime/pom.xml" }}
                    # Fallback to latest cache is an exact match is not found
                    - linkstone-

            - run: ./build-external.sh
            #- run: mvn -am -T 1C -B dependency:go-offline

            - save_cache:
                paths:
                - ~/.m2
                key: linkstone-{{ checksum "linkstone-shim/pom.xml" }}-{{ checksum "linkstone-runtime/pom.xml" }}

            # Ensure we are on the right repo before attempting a deploy
            - run: |
                if [ "${CIRCLE_PROJECT_USERNAME}" == "GlowstoneMC" ]; then
                  mvn -am -T 1C -B -s .circleci/maven.xml deploy
                else
                  mvn -am -T 1C -B package
                fi

            - store_artifacts:
                path: linkstone-shim/target/linkstone-shim-1.0.0.jar
                destination: linkstone-shim-1.0.0.jar

workflows:
    version: 2

    default-branch-build:
        jobs:
            - build-deploy:
                filters:
                    branches:
                      only: master

    other-branch-build:
        jobs:
            - build:
                filters:
                    branches:
                        ignore: master
